--- core
require("config.core.options")
require("config.core.keymaps")
require("config.core.autocmds")
require("config.core.terminal")

--- plugins
require("config.plugins.theme")
require("config.plugins.guess-indent")
require("config.plugins.direnv")
require("config.plugins.alpha")
require("config.plugins.treesitter")
require("config.plugins.fidget")
require("config.plugins.telescope")
require("config.plugins.which-key")
require("config.plugins.lsp")
require("config.plugins.mini")
require("config.plugins.conform")
require("config.plugins.noice")
require("config.plugins.lualine")
require("config.plugins.debug")
require("config.plugins.gitsigns")
require("config.plugins.diffview")
require("config.plugins.git-worktree")
require("config.plugins.grapple")
require("config.plugins.oil")
require("config.plugins.smart-splits")
require("config.plugins.flash")
require("config.plugins.kulala")
require("config.plugins.dadbod")
require("config.plugins.breadcrumb")
require("config.plugins.no-neck-pain")
