-- core
require("core.options")
require("core.keymaps")
require("core.autocmds")

-- plugins
require("modules.alpha")
require("modules.conform")
require("modules.diffview")
require("modules.git-worktree")
require("modules.gitsigns")
require("modules.gp")
require("modules.harpoon")
require("modules.lazygit")
require("modules.lsp")
require("modules.debug")
require("modules.lualine")
require("modules.mini")
require("modules.neo-tree")
require("modules.neotest")
require("modules.noice")
require("modules.oil")
require("modules.smart-splits")
require("modules.telescope")
require("modules.theme")
require("modules.tmux")
require("modules.treesitter")
require("modules.which-key")
require("modules.barbecue")
