vim.keymap.set("n", "<leader>gf", "<cmd>Git fetch<cr>", { desc = "[g]it [f]etch" })
vim.keymap.set("n", "<leader>gp", "<cmd>Git pull<cr>", { desc = "[g]it [p]ull" })
vim.keymap.set("n", "<leader>gP", "<cmd>Git push<cr>", { desc = "[g]it [P]ush" })
vim.keymap.set("n", "<leader>gs", "<cmd>rightbelow Git<cr>", { desc = "[g]it [s]tatus" })
vim.keymap.set("n", "<leader>gc", "<cmd>rightbelow Git commit<cr>", { desc = "[g]it [c]ommit" })
vim.keymap.set("n", "<leader>gC", "<cmd>rightbelow Git commit --amend<cr>", { desc = "[g]it [C]ommit (amend)" })
vim.keymap.set("n", "<leader>gl", "<cmd>rightbelow Git log<cr>", { desc = "[g]it [l]og" })
