--- core
require("config.core.options")
require("config.core.keymaps")
require("config.core.autocmds")

--- plugins
require("config.plugins.alpha")
require("config.plugins.conform")
require("config.plugins.diffview")
require("config.plugins.git-worktree")
require("config.plugins.gitsigns")
require("config.plugins.gp")
require("config.plugins.harpoon")
require("config.plugins.lazygit")
require("config.plugins.lsp")
require("config.plugins.debug")
require("config.plugins.lualine")
require("config.plugins.mini")
require("config.plugins.neo-tree")
require("config.plugins.neotest")
require("config.plugins.noice")
require("config.plugins.oil")
require("config.plugins.smart-splits")
require("config.plugins.telescope")
require("config.plugins.theme")
require("config.plugins.tmux")
require("config.plugins.treesitter")
require("config.plugins.which-key")
