--- core
require("config.core.options")
require("config.core.keymaps")
require("config.core.autocmds")

--- plugins
require("config.modules.alpha")
require("config.modules.conform")
require("config.modules.diffview")
require("config.modules.git-worktree")
require("config.modules.gitsigns")
require("config.modules.gp")
require("config.modules.harpoon")
require("config.modules.lazygit")
require("config.modules.lsp")
require("config.modules.debug")
require("config.modules.lualine")
require("config.modules.mini")
require("config.modules.neo-tree")
require("config.modules.neotest")
require("config.modules.noice")
require("config.modules.oil")
require("config.modules.smart-splits")
require("config.modules.telescope")
require("config.modules.theme")
require("config.modules.tmux")
require("config.modules.treesitter")
require("config.modules.which-key")
