-- core
require("core.options")
require("core.keymaps")
require("core.autocmds")

-- plugins
require("plugins.alpha")
require("plugins.conform")
require("plugins.diffview")
require("plugins.git-worktree")
require("plugins.gitsigns")
require("plugins.gp")
require("plugins.harpoon")
require("plugins.lazygit")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.mini")
require("plugins.neo-tree")
require("plugins.neotest")
require("plugins.noice")
require("plugins.oil")
require("plugins.smart-splits")
require("plugins.telescope")
require("plugins.theme")
require("plugins.tmux")
require("plugins.treesitter")
require("plugins.which-key")
