name: "health-check"

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "src/**"

jobs:
  health-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run . -- --headless "+checkhealth" +qa
