name: "pull-request"

on:
  pull_request:

jobs:
  health-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run . -- --headless "+checkhealth" +qa

  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    needs: [health-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: gh pr merge --rebase --auto
    env:
      GH_TOKEN: ${{ secrets.GH_REPO_PAT }}
